server:
    port: 8080

spring:
    application:
        name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
 
zuul:
  routes:
    order:
      path: /orders/**
      serviceId: order
    restaurant:
      path: /restaurants/**
      serviceId: restaurant
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "routes"